apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot-todo
spec:
  selector:
    matchLabels:
      app: java-springboot-todo
  replicas: 1
  template:
    metadata:
      labels:
        app: java-springboot-todo
    spec:
      containers:
        - name: java-springboot-todo
          image: java-springboot-todo:latest
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_USERNAME # Setting Database username from configmap
              valueFrom:
                configMapKeyRef:
                  name: springboot-todo-config
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: springboot-todo-secrets
                  key: password
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-crud-svc
spec:
  selector:
    app: java-springboot-todo
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: ClusterIP # type of the service.

