apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot-todo
spec:
  selector:
    matchLabels:
      app: java-springboot-todo
  replicas: 1
  template:
    metadata:
      labels:
        app: java-springboot-todo
    spec:
      containers:
        - name: java-springboot-todo
          image: sbathuru/java-springboot-todo:latest
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: K8S_UNAME_CONFIGMAP # Setting Database username from configmap
              valueFrom:
                configMapKeyRef:
                  name: java-springboot-todo-configmap
                  key: username
            - name: K8S_PASSWORD_SECRET # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: java-springboot-todo-secrets
                  key: password
